fix many bugs

diff --git a/.github/workflows/Archiver.yml b/.github/workflows/Archiver.yml
--- a/.github/workflows/Archiver.yml
+++ b/.github/workflows/Archiver.yml
@@ -68,9 +68,10 @@ jobs:
         id: download
         run: |
           cd ${{ github.workspace }}
-          python3 Archiver.py
+          python3 Archiver.py || echo "failed=true" >> $GITHUB_OUTPUT
       
       - name: Check if release exists 🤔
+        if: steps.download.outputs.failed != 'true'
         id: check_release
         run: |
           latest_tag=$(curl -sL https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
@@ -112,7 +113,7 @@ jobs:
           echo "SHA256=$sha256_hash_lower"
           
       - name: Update build to release 🤌
-        if: steps.check_release.outputs.isPrerelease == 'false'
+        if: steps.check_release.outputs.isPrerelease == 'false' 
         uses: softprops/action-gh-release@v0.1.15
         with:
           files: ${{ github.workspace }}/download/${{ steps.download.outputs.Filename }}
